KIT ;
  IDL VERSION 1.2.8 ;
  TITLE 'hole-flanging-by-SPIF-in-a-single-stage' ;
  AUTHOR 'Domingo Morales-Palma' ;
  CREATION DATE 6/4/2022 ;
  PROJECT NAME 'MfM' ;

  MODEL 'hole-flanging-by-SPIF-in-a-single-stage'
    {LWI
    F 0 -13 0 0 0 400
      0 0 0 204 3 2 1 34
      100 'Arial'
    F 1 -24 0 0 0 400
      0 0 0 204 3 2 1 34
      190 'Arial'
    F 2 -11 0 0 0 400
      0 0 0 204 3 2 1 34
      80 'Courier New'
    F 3 -8 0 0 0 400
      0 0 0 204 3 2 1 34
      60 'Dialog'
    F 4 -10 0 0 0 400
      0 0 0 204 3 2 1 34
      80 'Dialog'
    D 0 0 0 0 0 1 0 0 2
    G 0 1
    T 'WORKING'
    R 77
    M 0 }
   ;
    AUTHOR 'Domingo Morales-Palma' ;
    PROJECT NAME 'MfM' ;
    DIAGRAM GRAPHIC A-0 ;
      CREATION DATE 30/3/2022 ;
      REVISION DATE 30/3/2022 ;
      TITLE 'hole-flanging-by-SPIF-in-a-single-stage' ;
      STATUS WORKING ;

      BOX 0 ;
        NAME '{LWI I 4 255 255 255}Analyze Flangeability of AA7075-O Sheets in Hole Flanging by Single Stage SPIF' ;
        BOX COORDINATES (0.298,0.642) (0.634,0.306) ;
        DETAIL REFERENCE N A0 ;
      ENDBOX ;
      ARROWSEG 1 ;
        SOURCE BORDER ;
        PATH (0.019,0.498)(0.298,0.498) ;
        LABEL '{LWI I 0 255 255 }Part Model' ;
        LABEL COORDINATES (0.156,0.51) ;
        SINK BOX 0I1 ;
      ENDSEG ;
      ARROWSEG 2 ;
        SOURCE BOX 0O1 ;
        PATH (0.634,0.402)(0.977,0.402) ;
        LABEL '{LWI I 0 255 255 }NC<CR>Program' ;
        LABEL COORDINATES (0.805,0.42) ;
        SINK BORDER ;
      ENDSEG ;
      ARROWSEG 3 ;
        SOURCE BOX 0O2 ;
        PATH (0.634,0.344)(0.977,0.344) ;
        LABEL '{LWI I 0 255 255 }Part Model' ;
        LABEL COORDINATES (0.805,0.365) ;
        SINK BORDER ;
      ENDSEG ;
      ARROWSEG 4 ;
        SOURCE BOX 0O3 ;
        PATH (0.634,0.545)(0.977,0.545) ;
        LABEL '{LWI I 0 255 255 }Analysis<CR>Results' ;
        LABEL COORDINATES (0.805,0.565) ;
        SINK BORDER ;
      ENDSEG ;
      ARROWSEG 5 ;
        SOURCE BOX 0O4 ;
        PATH (0.634,0.603)(0.977,0.603) ;
        LABEL '{LWI I 0 255 255 }Conclusions' ;
        LABEL COORDINATES (0.8,0.629) ;
        SINK BORDER ;
      ENDSEG ;
      ARROWSEG 6 ;
        SOURCE BORDER ;
        PATH (0.332,0.968)(0.332,0.642) ;
        LABEL '{LWI I 0 255 255 }Math<CR>Equation<CR>Solver' ;
        LABEL COORDINATES (0.332,0.829) ;
        SINK BOX 0M1 ;
      ENDSEG ;
      ARROWSEG 7 ;
        SOURCE BORDER ;
        PATH (0.398,0.968)(0.398,0.642) ;
        LABEL '{LWI I 0 255 255 }CAD-CAM<CR>System' ;
        LABEL COORDINATES (0.4,0.829) ;
        SINK BOX 0M2 ;
      ENDSEG ;
      ARROWSEG 8 ;
        SOURCE BORDER ;
        PATH (0.461,0.968)(0.461,0.642) ;
        LABEL '{LWI I 0 255 255 }NC Post-<CR>processor' ;
        LABEL COORDINATES (0.463,0.828) ;
        SINK BOX 0M3 ;
      ENDSEG ;
      ARROWSEG 9 ;
        SOURCE BORDER ;
        PATH (0.523,0.968)(0.523,0.642) ;
        LABEL '{LWI I 0 255 255 }User<CR>Interface' ;
        LABEL COORDINATES (0.522,0.829) ;
        SINK BOX 0M4 ;
      ENDSEG ;
      ARROWSEG 10 ;
        SOURCE BORDER ;
        PATH (0.576,0.968)(0.576,0.642) ;
        LABEL '{LWI I 0 255 255 }Data<CR>Processing<CR>System' ;
        LABEL COORDINATES (0.576,0.829) ;
        SINK BOX 0M5 ;
      ENDSEG ;
      ARROWSEG 11 ;
        SOURCE BORDER ;
        PATH (0.345,0.031)(0.345,0.306) ;
        LABEL '{LWI I 0 255 255 }Blank<CR>Model' ;
        LABEL COORDINATES (0.347,0.192) ;
        SINK BOX 0C1 ;
      ENDSEG ;
      ARROWSEG 12 ;
        SOURCE BORDER ;
        PATH (0.419,0.031)(0.419,0.306) ;
        LABEL '{LWI I 0 255 255 }Forming<CR>Tool<CR>Model' ;
        LABEL COORDINATES (0.425,0.192) ;
        SINK BOX 0C2 ;
      ENDSEG ;
      ARROWSEG 13 ;
        SOURCE BOX 0O5 ;
        PATH (0.634,0.483)(0.977,0.483) ;
        LABEL '{LWI I 0 255 255 }Test<CR>Results' ;
        LABEL COORDINATES (0.805,0.501) ;
        SINK BORDER ;
      ENDSEG ;
      ARROWSEG 14 ;
        SOURCE BORDER ;
        PATH (0.57,0.031)(0.57,0.306) ;
        LABEL '{LWI I 0 255 255 }Material<CR>Properties' ;
        LABEL COORDINATES (0.571,0.192) ;
        SINK BOX 0C3 ;
      ENDSEG ;
      ARROWSEG 15 ;
        SOURCE BORDER ;
        PATH (0.5,0.031)(0.5,0.306) ;
        LABEL '{LWI I 0 255 255 }Forming<CR>Conditions' ;
        LABEL COORDINATES (0.498,0.192) ;
        SINK BOX 0C4 ;
      ENDSEG ;
    ENDDIAGRAM ;
    DIAGRAM GRAPHIC A0 ;
      CREATION DATE 30/3/2022 ;
      REVISION DATE 30/3/2022 ;
      TITLE 'Analyze Flangeability of AA7075-O Sheets in Hole Flanging by Single Stage SPIF' ;
      STATUS WORKING ;

      BOX 1 ;
        NAME '{LWI I 4 255 255 255}Define NC Program' ;
        BOX COORDINATES (0.108,0.306) (0.303,0.188) ;
        DETAIL REFERENCE N A1 ;
      ENDBOX ;
      BOX 2 ;
        NAME '{LWI I 4 255 255 255}Perform Experiment' ;
        BOX COORDINATES (0.4,0.57) (0.6,0.451) ;
        DETAIL REFERENCE N A2 ;
      ENDBOX ;
      BOX 3 ;
        NAME '{LWI I 4 255 255 255}Analyze Experimental Results' ;
        BOX COORDINATES (0.664,0.824) (0.869,0.706) ;
        DETAIL REFERENCE N A3 ;
      ENDBOX ;
      ARROWSEG 1 ;
        SOURCE BORDER I1 (0.019,0.248) ;
        PATH (0.019,0.248)(0.108,0.248) ;
        LABEL '{LWI I 0 255 255 }Part Model' ;
        LABEL COORDINATES (0.044,0.265) ;
        SINK BOX 1I1 ;
      ENDSEG ;
      ARROWSEG 2 ;
        SOURCE BOX 1O1 ;
        PATH (0.303,0.268)(0.977,0.268) ;
        LABEL '{LWI I 0 255 255 }NC<CR>Program' ;
        LABEL COORDINATES (0.937,0.292) ;
        SINK BRANCH 4 3 ;
      ENDSEG ;
      ARROWSEG 3 ;
        SOURCE BRANCH 2 ;
        PATH (0.526,0.27)(0.977,0.27) ;
        LABEL 'NC Program' ;
        SINK BORDER O1 (0.977,0.27) ;
      ENDSEG ;
      ARROWSEG 4 ;
        SOURCE BRANCH 2 ;
        PATH (0.526,0.27)(0.526,0.451) ;
        LABEL 'NC Program' ;
        SINK BOX 2C1 ;
      ENDSEG ;
      ARROWSEG 5 ;
        SOURCE BOX 1O2 ;
        PATH (0.303,0.229)(0.779,0.229) ;
        LABEL '{LWI I 0 255 255 }Part Model' ;
        LABEL COORDINATES (0.932,0.238) ;
        SINK BRANCH 26 25 ;
      ENDSEG ;
      ARROWSEG 6 ;
        SOURCE BOX 3O1 ;
        PATH (0.869,0.77)(0.977,0.77) ;
        LABEL '{LWI I 0 255 255 }Analysis<CR>Results' ;
        LABEL COORDINATES (0.937,0.738) ;
        SINK BORDER O3 (0.977,0.77) ;
      ENDSEG ;
      ARROWSEG 7 ;
        SOURCE BOX 3O2 ;
        PATH (0.869,0.798)(0.977,0.798) ;
        LABEL '{LWI I 0 255 255 }Conclusions' ;
        LABEL COORDINATES (0.927,0.829) ;
        SINK BORDER O4 (0.977,0.798) ;
      ENDSEG ;
      ARROWSEG 8 ;
        SOURCE BORDER M1 (0.146,0.968) ;
        PATH (0.146,0.968)(0.146,0.306) ;
        LABEL '{LWI I 0 255 255 }Math<CR>Equation<CR>Solver' ;
        LABEL COORDINATES (0.098,0.92) ;
        SINK BOX 1M1 ;
      ENDSEG ;
      ARROWSEG 9 ;
        SOURCE BORDER M2 (0.208,0.968) ;
        PATH (0.208,0.968)(0.208,0.306) ;
        LABEL '{LWI I 0 255 255 }CAD-CAM<CR>System' ;
        LABEL COORDINATES (0.156,0.929) ;
        SINK BOX 1M2 ;
      ENDSEG ;
      ARROWSEG 10 ;
        SOURCE BORDER M3 (0.267,0.968) ;
        PATH (0.267,0.968)(0.267,0.306) ;
        LABEL '{LWI I 0 255 255 }NC Post-<CR>processor' ;
        LABEL COORDINATES (0.275,0.938) ;
        SINK BOX 1M3 ;
      ENDSEG ;
      ARROWSEG 11 ;
        SOURCE BORDER M4 (0.504,0.968) ;
        PATH (0.504,0.968)(0.504,0.57) ;
        LABEL '{LWI I 0 255 255 }User<CR>Interface' ;
        LABEL COORDINATES (0.512,0.938) ;
        SINK BOX 2M1 ;
      ENDSEG ;
      ARROWSEG 12 ;
        SOURCE BORDER M5 (0.761,0.968) ;
        PATH (0.761,0.968)(0.761,0.824) ;
        LABEL '{LWI I 0 255 255 }Data<CR>Processing<CR>System' ;
        LABEL COORDINATES (0.756,0.929) ;
        SINK BOX 3M1 ;
      ENDSEG ;
      ARROWSEG 13 ;
        SOURCE BORDER C1 (0.445,0.031) ;
        PATH (0.445,0.031)(0.445,0.131) ;
        LABEL '{LWI I 0 255 255 }Blank<CR>Model' ;
        LABEL COORDINATES (0.415,0.065) ;
        SINK BRANCH 22 24 23 ;
      ENDSEG ;
      ARROWSEG 14 ;
        SOURCE BORDER C2 (0.159,0.031) ;
        PATH (0.159,0.031)(0.159,0.188) ;
        LABEL '{LWI I 0 255 255 }Forming<CR>Tool<CR>Model' ;
        LABEL COORDINATES (0.112,0.083) ;
        SINK BOX 1C1 ;
      ENDSEG ;
      ARROWSEG 15 ;
        SOURCE BOX 2O1 ;
        PATH (0.6,0.48)(0.638,0.48) ;
        LABEL '{LWI I 0 255 255 }Test<CR>Results' ;
        LABEL COORDINATES (0.937,0.501) ;
        SINK BRANCH 17 16 ;
      ENDSEG ;
      ARROWSEG 16 ;
        SOURCE BRANCH 15 ;
        PATH (0.638,0.48)(0.908,0.48) ;
        LABEL 'Test Results' ;
        SINK JOIN 18 ;
      ENDSEG ;
      ARROWSEG 17 ;
        SOURCE BRANCH 15 ;
        PATH (0.638,0.48)(0.638,0.758)(0.664,0.758) ;
        LABEL 'Test Results' ;
        SINK BOX 3I1 ;
      ENDSEG ;
      ARROWSEG 18 ;
        SOURCE JOIN 16 19 ;
        PATH (0.908,0.48)(0.977,0.48) ;
        LABEL 'Test Results' ;
        SINK BORDER O5 (0.977,0.48) ;
      ENDSEG ;
      ARROWSEG 19 ;
        SOURCE BOX 3O3 ;
        PATH (0.869,0.736)(0.908,0.736)(0.908,0.48) ;
        LABEL 'Test Results' ;
        SINK JOIN 18 ;
      ENDSEG ;
      ARROWSEG 20 ;
        SOURCE BORDER C3 (0.835,0.031) ;
        PATH (0.835,0.031)(0.835,0.706) ;
        LABEL '{LWI I 0 255 255 }Material<CR>Properties' ;
        LABEL COORDINATES (0.834,0.083) ;
        SINK BOX 3C1 ;
      ENDSEG ;
      ARROWSEG 21 ;
        SOURCE BORDER C4 (0.211,0.031) ;
        PATH (0.211,0.031)(0.211,0.188) ;
        LABEL '{LWI I 0 255 255 }Forming<CR>Conditions' ;
        LABEL COORDINATES (0.19,0.074) ;
        SINK BOX 1C2 ;
      ENDSEG ;
      ARROWSEG 22 ;
        SOURCE BRANCH 13 ;
        PATH (0.445,0.131)(0.445,0.451) ;
        LABEL 'Blank Model' ;
        SINK BOX 2C2 ;
      ENDSEG ;
      ARROWSEG 23 ;
        SOURCE BRANCH 13 ;
        PATH (0.445,0.131)(0.246,0.131)(0.246,0.188) ;
        LABEL 'Blank Model' ;
        SINK BOX 1C3 ;
      ENDSEG ;
      ARROWSEG 24 ;
        SOURCE BRANCH 13 ;
        PATH (0.445,0.131)(0.728,0.131)(0.728,0.706) ;
        LABEL 'Blank Model' ;
        SINK BOX 3C2 ;
      ENDSEG ;
      ARROWSEG 25 ;
        SOURCE BRANCH 5 ;
        PATH (0.779,0.229)(0.977,0.229) ;
        LABEL 'Part Model' ;
        SINK BORDER O2 (0.977,0.229) ;
      ENDSEG ;
      ARROWSEG 26 ;
        SOURCE BRANCH 5 ;
        PATH (0.779,0.229)(0.779,0.706) ;
        LABEL 'Part Model' ;
        SINK BOX 3C3 ;
      ENDSEG ;
    ENDDIAGRAM ;
    DIAGRAM GRAPHIC A1 ;
      CREATION DATE 30/3/2022 ;
      REVISION DATE 30/3/2022 ;
      TITLE 'Define NC Program' ;
      STATUS WORKING ;

      BOX 1 ;
        NAME '{LWI I 4 255 255 255}Predict Part Height' ;
        BOX COORDINATES (0.108,0.311) (0.195,0.197) ;
        DETAIL REFERENCE N A11 ;
      ENDBOX ;
      BOX 2 ;
        NAME '{LWI I 4 255 255 255}Calculate Tool Path' ;
        BOX COORDINATES (0.371,0.57) (0.547,0.451) ;
        DETAIL REFERENCE N A12 ;
      ENDBOX ;
      BOX 3 ;
        NAME '{LWI I 4 255 255 255}Generate G-Code' ;
        BOX COORDINATES (0.747,0.824) (0.903,0.706) ;
        DETAIL REFERENCE N A13 ;
      ENDBOX ;
      ARROWSEG 1 ;
        SOURCE BORDER I1 (0.019,0.258) ;
        PATH (0.019,0.258)(0.108,0.258) ;
        LABEL '{LWI I 0 255 255 }Part Model' ;
        LABEL COORDINATES (0.03,0.238) ;
        SINK BOX 1I1 ;
      ENDSEG ;
      ARROWSEG 2 ;
        SOURCE BOX 1O1 ;
        PATH (0.195,0.262)(0.401,0.262) ;
        LABEL 'Part Model' ;
        SINK BRANCH 6 5 ;
      ENDSEG ;
      ARROWSEG 3 ;
        SOURCE BOX 2O1 ;
        PATH (0.547,0.496)(0.682,0.496)(0.682,0.773)(0.747,0.773) ;
        LABEL '{LWI I 0 255 255 }Tool Path' ;
        LABEL COORDINATES (0.683,0.647) ;
        SINK BOX 3I1 ;
      ENDSEG ;
      ARROWSEG 4 ;
        SOURCE BOX 3O1 ;
        PATH (0.903,0.771)(0.977,0.771) ;
        LABEL '{LWI I 0 255 255 }NC<CR>Program' ;
        LABEL COORDINATES (0.937,0.747) ;
        SINK BORDER O1 (0.977,0.771) ;
      ENDSEG ;
      ARROWSEG 5 ;
        SOURCE BRANCH 2 ;
        PATH (0.401,0.262)(0.977,0.262) ;
        LABEL '{LWI I 0 255 255 }Part Model' ;
        LABEL COORDINATES (0.932,0.292) ;
        SINK BORDER O2 (0.977,0.262) ;
      ENDSEG ;
      ARROWSEG 6 ;
        SOURCE BRANCH 2 ;
        PATH (0.401,0.262)(0.401,0.451) ;
        LABEL 'Part Model' ;
        SINK BOX 2C1 ;
      ENDSEG ;
      ARROWSEG 7 ;
        SOURCE BORDER M1 (0.15,0.968) ;
        PATH (0.15,0.968)(0.15,0.311) ;
        LABEL '{LWI I 0 255 255 }Math<CR>Equation<CR>Solver' ;
        LABEL COORDINATES (0.103,0.947) ;
        SINK BOX 1M1 ;
      ENDSEG ;
      ARROWSEG 8 ;
        SOURCE BORDER M2 (0.459,0.968) ;
        PATH (0.459,0.968)(0.459,0.57) ;
        LABEL '{LWI I 0 255 255 }CAD-CAM<CR>System' ;
        LABEL COORDINATES (0.473,0.929) ;
        SINK BOX 2M1 ;
      ENDSEG ;
      ARROWSEG 9 ;
        SOURCE BORDER M3 (0.829,0.968) ;
        PATH (0.829,0.968)(0.829,0.824) ;
        LABEL '{LWI I 0 255 255 }NC Post-<CR>processor' ;
        LABEL COORDINATES (0.859,0.957) ;
        SINK BOX 3M1 ;
      ENDSEG ;
      ARROWSEG 10 ;
        SOURCE BORDER C1 (0.453,0.031) ;
        PATH (0.453,0.031)(0.453,0.135) ;
        LABEL '{LWI I 0 255 255 }Forming<CR>Tool<CR>Model' ;
        LABEL COORDINATES (0.4,0.074) ;
        SINK BRANCH 12 11 ;
      ENDSEG ;
      ARROWSEG 11 ;
        SOURCE BRANCH 10 ;
        PATH (0.453,0.135)(0.453,0.451) ;
        LABEL 'Forming Tool Model' ;
        SINK BOX 2C2 ;
      ENDSEG ;
      ARROWSEG 12 ;
        SOURCE BRANCH 10 ;
        PATH (0.453,0.135)(0.163,0.135)(0.163,0.197) ;
        LABEL 'Forming Tool Model' ;
        SINK BOX 1C1 ;
      ENDSEG ;
      ARROWSEG 13 ;
        SOURCE BORDER C2 (0.507,0.031) ;
        PATH (0.507,0.031)(0.507,0.451) ;
        LABEL '{LWI I 0 255 255 }Forming<CR>Conditions' ;
        LABEL COORDINATES (0.508,0.083) ;
        SINK BOX 2C3 ;
      ENDSEG ;
      ARROWSEG 14 ;
        SOURCE BORDER C3 (0.138,0.031) ;
        PATH (0.138,0.031)(0.138,0.197) ;
        LABEL '{LWI I 0 255 255 }Blank<CR>Model' ;
        LABEL COORDINATES (0.147,0.065) ;
        SINK BOX 1C2 ;
      ENDSEG ;
    ENDDIAGRAM ;
    DIAGRAM GRAPHIC A2 ;
      CREATION DATE 30/3/2022 ;
      REVISION DATE 30/3/2022 ;
      TITLE 'Perform Experiment' ;
      STATUS WORKING ;

      BOX 1 ;
        NAME '{LWI I 4 255 255 255}Prepare Specimen' ;
        BOX COORDINATES (0.069,0.315) (0.195,0.197) ;
        DETAIL REFERENCE N A21 ;
      ENDBOX ;
      BOX 2 ;
        NAME '{LWI I 4 255 255 255}Perform Hole Flanging Test' ;
        BOX COORDINATES (0.381,0.57) (0.576,0.451) ;
        DETAIL REFERENCE N A22 ;
      ENDBOX ;
      BOX 3 ;
        NAME '{LWI I 4 255 255 255}Measure Specimen' ;
        BOX COORDINATES (0.698,0.824) (0.854,0.706) ;
        DETAIL REFERENCE N A23 ;
      ENDBOX ;
      ARROWSEG 1 ;
        SOURCE BORDER C1 (0.493,0.031) ;
        PATH (0.493,0.031)(0.493,0.451) ;
        LABEL '{LWI I 0 255 255 }NC<CR>Program' ;
        LABEL COORDINATES (0.508,0.083) ;
        SINK BOX 2C1 ;
      ENDSEG ;
      ARROWSEG 2 ;
        SOURCE BOX 1O1 ;
        PATH (0.195,0.247)(0.281,0.247)(0.281,0.521)(0.381,0.521) ;
        LABEL '{LWI I 0 255 255 }Specimen' ;
        LABEL COORDINATES (0.21,0.229) ;
        SINK BOX 2I1 ;
      ENDSEG ;
      ARROWSEG 3 ;
        SOURCE BORDER M1 (0.489,0.968) ;
        PATH (0.489,0.968)(0.489,0.882) ;
        LABEL '{LWI I 0 255 255 }User<CR>Interface' ;
        LABEL COORDINATES (0.508,0.956) ;
        SINK BRANCH 4 6 5 ;
      ENDSEG ;
      ARROWSEG 4 ;
        SOURCE BRANCH 3 ;
        PATH (0.489,0.882)(0.489,0.57) ;
        LABEL 'User Interface' ;
        SINK BOX 2M1 ;
      ENDSEG ;
      ARROWSEG 5 ;
        SOURCE BRANCH 3 ;
        PATH (0.489,0.882)(0.12,0.882)(0.12,0.315) ;
        LABEL 'User Interface' ;
        SINK BOX 1M1 ;
      ENDSEG ;
      ARROWSEG 6 ;
        SOURCE BRANCH 3 ;
        PATH (0.489,0.882)(0.768,0.882)(0.768,0.824) ;
        LABEL 'User Interface' ;
        SINK BOX 3M1 ;
      ENDSEG ;
      ARROWSEG 7 ;
        SOURCE BORDER C2 (0.122,0.031) ;
        PATH (0.122,0.031)(0.122,0.197) ;
        LABEL '{LWI I 0 255 255 }Blank<CR>Model' ;
        LABEL COORDINATES (0.127,0.074) ;
        SINK BOX 1C1 ;
      ENDSEG ;
      ARROWSEG 8 ;
        SOURCE BOX 2O1 ;
        PATH (0.576,0.522)(0.634,0.522) ;
        LABEL '{LWI I 0 255 255 }Test<CR>Results' ;
        LABEL COORDINATES (0.937,0.583) ;
        SINK BRANCH 10 9 ;
      ENDSEG ;
      ARROWSEG 9 ;
        SOURCE BRANCH 8 ;
        PATH (0.634,0.522)(0.905,0.522) ;
        LABEL 'Test Results' ;
        SINK JOIN 11 ;
      ENDSEG ;
      ARROWSEG 10 ;
        SOURCE BRANCH 8 ;
        PATH (0.634,0.522)(0.634,0.764)(0.698,0.764) ;
        LABEL 'Test Results' ;
        SINK BOX 3I1 ;
      ENDSEG ;
      ARROWSEG 11 ;
        SOURCE JOIN 9 12 ;
        PATH (0.905,0.522)(0.977,0.522) ;
        LABEL 'Test Results' ;
        SINK BORDER O1 (0.977,0.522) ;
      ENDSEG ;
      ARROWSEG 12 ;
        SOURCE BOX 3O1 ;
        PATH (0.854,0.763)(0.905,0.763)(0.905,0.522) ;
        LABEL 'Test Results' ;
        SINK JOIN 11 ;
      ENDSEG ;
    ENDDIAGRAM ;
    DIAGRAM GRAPHIC A3 ;
      CREATION DATE 30/3/2022 ;
      REVISION DATE 30/3/2022 ;
      TITLE 'Analyze Experimental Results' ;
      STATUS WORKING ;

      BOX 1 ;
        NAME '{LWI I 4 255 255 255}Process Test Data' ;
        BOX COORDINATES (0.108,0.315) (0.259,0.197) ;
        DETAIL REFERENCE N A31 ;
      ENDBOX ;
      BOX 2 ;
        NAME '{LWI I 4 255 255 255}Analyze Test Results' ;
        BOX COORDINATES (0.386,0.57) (0.571,0.451) ;
        DETAIL REFERENCE N A32 ;
      ENDBOX ;
      BOX 3 ;
        NAME '{LWI I 4 255 255 255}Induce Conclusions' ;
        BOX COORDINATES (0.669,0.824) (0.844,0.706) ;
        DETAIL REFERENCE N A33 ;
      ENDBOX ;
      ARROWSEG 1 ;
        SOURCE BOX 2O1 ;
        PATH (0.571,0.503)(0.76,0.503) ;
        LABEL '{LWI I 0 255 255 }Analysis<CR>Results' ;
        LABEL COORDINATES (0.937,0.529) ;
        SINK BRANCH 4 3 ;
      ENDSEG ;
      ARROWSEG 2 ;
        SOURCE BOX 3O1 ;
        PATH (0.844,0.772)(0.977,0.772) ;
        LABEL '{LWI I 0 255 255 }Conclusions' ;
        LABEL COORDINATES (0.927,0.801) ;
        SINK BORDER O2 (0.977,0.772) ;
      ENDSEG ;
      ARROWSEG 3 ;
        SOURCE BRANCH 1 ;
        PATH (0.76,0.503)(0.977,0.503) ;
        LABEL 'Analysis Results' ;
        SINK BORDER O1 (0.977,0.503) ;
      ENDSEG ;
      ARROWSEG 4 ;
        SOURCE BRANCH 1 ;
        PATH (0.76,0.503)(0.76,0.706) ;
        LABEL 'Analysis Results' ;
        SINK BOX 3C1 ;
      ENDSEG ;
      ARROWSEG 5 ;
        SOURCE BORDER M1 (0.192,0.968) ;
        PATH (0.192,0.968)(0.192,0.878) ;
        LABEL '{LWI I 0 255 255 }Data<CR>Processing<CR>System' ;
        LABEL COORDINATES (0.161,0.929) ;
        SINK BRANCH 9 8 ;
      ENDSEG ;
      ARROWSEG 6 ;
        SOURCE BRANCH 8 ;
        PATH (0.192,0.876)(0.192,0.315) ;
        LABEL 'Data Processing System' ;
        SINK BOX 1M1 ;
      ENDSEG ;
      ARROWSEG 7 ;
        SOURCE BRANCH 8 ;
        PATH (0.192,0.876)(0.491,0.876)(0.491,0.57) ;
        LABEL 'Data Processing System' ;
        SINK BOX 2M1 ;
      ENDSEG ;
      ARROWSEG 8 ;
        SOURCE BRANCH 5 ;
        PATH (0.192,0.878)(0.192,0.876) ;
        LABEL 'Data Processing System' ;
        SINK BRANCH 7 6 ;
      ENDSEG ;
      ARROWSEG 9 ;
        SOURCE BRANCH 5 ;
        PATH (0.192,0.878)(0.764,0.878)(0.764,0.824) ;
        LABEL 'Data Processing System' ;
        SINK BOX 3M1 ;
      ENDSEG ;
      ARROWSEG 10 ;
        SOURCE BORDER I1 (0.019,0.253) ;
        PATH (0.019,0.253)(0.108,0.253) ;
        LABEL '{LWI I 0 255 255 }Test<CR>Results' ;
        LABEL COORDINATES (0.034,0.283) ;
        SINK BOX 1I1 ;
      ENDSEG ;
      ARROWSEG 11 ;
        SOURCE BRANCH 12 ;
        PATH (0.433,0.257)(0.977,0.257) ;
        LABEL 'Test Results' ;
        SINK BORDER O3 (0.977,0.257) ;
      ENDSEG ;
      ARROWSEG 12 ;
        SOURCE BOX 1O1 ;
        PATH (0.259,0.257)(0.433,0.257) ;
        LABEL '{LWI I 0 255 255 }Test<CR>Results' ;
        LABEL COORDINATES (0.922,0.229) ;
        SINK BRANCH 11 13 ;
      ENDSEG ;
      ARROWSEG 13 ;
        SOURCE BRANCH 12 ;
        PATH (0.433,0.257)(0.433,0.451) ;
        LABEL 'Test Results' ;
        SINK BOX 2C1 ;
      ENDSEG ;
      ARROWSEG 14 ;
        SOURCE BORDER C1 (0.503,0.031) ;
        PATH (0.503,0.031)(0.503,0.451) ;
        LABEL '{LWI I 0 255 255 }Material<CR>Properties' ;
        LABEL COORDINATES (0.517,0.074) ;
        SINK BOX 2C2 ;
      ENDSEG ;
      ARROWSEG 15 ;
        SOURCE BORDER C2 (0.164,0.031) ;
        PATH (0.164,0.031)(0.164,0.197) ;
        LABEL '{LWI I 0 255 255 }Blank<CR>Model' ;
        LABEL COORDINATES (0.171,0.083) ;
        SINK BOX 1C1 ;
      ENDSEG ;
      ARROWSEG 16 ;
        SOURCE BORDER C3 (0.217,0.031) ;
        PATH (0.217,0.031)(0.217,0.197) ;
        LABEL '{LWI I 0 255 255 }Part Model' ;
        LABEL COORDINATES (0.23,0.074) ;
        SINK BOX 1C2 ;
      ENDSEG ;
    ENDDIAGRAM ;
    DIAGRAM GRAPHIC A32 ;
      CREATION DATE 30/3/2022 ;
      REVISION DATE 30/3/2022 ;
      TITLE 'Analyze Test Results' ;
      STATUS WORKING ;

      BOX 1 ;
        NAME '{LWI I 4 255 255 255}Calculate LFR' ;
        BOX COORDINATES (0.093,0.315) (0.21,0.197) ;
        DETAIL REFERENCE N A321 ;
      ENDBOX ;
      BOX 2 ;
        NAME '{LWI I 4 255 255 255}Plot FLD' ;
        BOX COORDINATES (0.395,0.551) (0.571,0.433) ;
        DETAIL REFERENCE N A322 ;
      ENDBOX ;
      BOX 3 ;
        NAME '{LWI I 4 255 255 255}Calculate Technological Parameters and Plot Diagrams' ;
        BOX COORDINATES (0.605,0.824) (0.81,0.688) ;
        DETAIL REFERENCE N A323 ;
      ENDBOX ;
      ARROWSEG 1 ;
        SOURCE BORDER C1 (0.427,0.031) ;
        PATH (0.427,0.031)(0.427,0.147) ;
        LABEL '{LWI I 0 255 255 }Test<CR>Results' ;
        LABEL COORDINATES (0.43,0.074) ;
        SINK BRANCH 16 15 ;
      ENDSEG ;
      ARROWSEG 2 ;
        SOURCE BORDER M1 (0.475,0.968) ;
        PATH (0.475,0.968)(0.475,0.91) ;
        LABEL '{LWI I 0 255 255 }Data<CR>Processing<CR>System' ;
        LABEL COORDINATES (0.488,0.947) ;
        SINK BRANCH 12 11 ;
      ENDSEG ;
      ARROWSEG 3 ;
        SOURCE BOX 1O1 ;
        PATH (0.21,0.241)(0.889,0.241)(0.889,0.541)(0.891,0.541) ;
        LABEL '{LWI I 0 255 255 }LFR' ;
        LABEL COORDINATES (0.898,0.331) ;
        SINK JOIN 5 ;
      ENDSEG ;
      ARROWSEG 4 ;
        SOURCE BORDER C2 (0.521,0.031) ;
        PATH (0.521,0.031)(0.521,0.433) ;
        LABEL '{LWI I 0 255 255 }Material<CR>Properties' ;
        LABEL COORDINATES (0.522,0.065) ;
        SINK BOX 2C1 ;
      ENDSEG ;
      ARROWSEG 5 ;
        SOURCE JOIN 6 3 ;
        PATH (0.891,0.541)(0.906,0.541) ;
        LABEL '{LWI I 0 255 255 }Analysis<CR>Results' ;
        LABEL COORDINATES (0.927,0.547) ;
        SINK JOIN 7 ;
      ENDSEG ;
      ARROWSEG 6 ;
        SOURCE BOX 2O1 ;
        PATH (0.571,0.486)(0.891,0.486)(0.891,0.541) ;
        LABEL '{LWI I 0 255 255 }FLD' ;
        LABEL COORDINATES (0.796,0.501) ;
        SINK JOIN 5 ;
      ENDSEG ;
      ARROWSEG 7 ;
        SOURCE JOIN 5 8 ;
        PATH (0.906,0.541)(0.977,0.541) ;
        LABEL 'Analysis Results' ;
        SINK BORDER O1 (0.977,0.541) ;
      ENDSEG ;
      ARROWSEG 8 ;
        SOURCE BOX 3O1 ;
        PATH (0.81,0.756)(0.906,0.756)(0.906,0.541) ;
        LABEL '{LWI I 0 255 255 }Technological<CR>Parameters' ;
        LABEL COORDINATES (0.825,0.792) ;
        SINK JOIN 7 ;
      ENDSEG ;
      ARROWSEG 9 ;
        SOURCE BRANCH 11 ;
        PATH (0.475,0.898)(0.475,0.551) ;
        LABEL 'Data Processing System' ;
        SINK BOX 2M1 ;
      ENDSEG ;
      ARROWSEG 10 ;
        SOURCE BRANCH 11 ;
        PATH (0.475,0.898)(0.708,0.898)(0.708,0.824) ;
        LABEL 'Data Processing System' ;
        SINK BOX 3M1 ;
      ENDSEG ;
      ARROWSEG 11 ;
        SOURCE BRANCH 2 ;
        PATH (0.475,0.91)(0.475,0.898) ;
        LABEL 'Data Processing System' ;
        SINK BRANCH 10 9 ;
      ENDSEG ;
      ARROWSEG 12 ;
        SOURCE BRANCH 2 ;
        PATH (0.475,0.91)(0.145,0.91)(0.145,0.315) ;
        LABEL 'Data Processing System' ;
        SINK BOX 1M1 ;
      ENDSEG ;
      ARROWSEG 13 ;
        SOURCE BRANCH 15 ;
        PATH (0.427,0.149)(0.427,0.433) ;
        LABEL 'Test Results' ;
        SINK BOX 2C2 ;
      ENDSEG ;
      ARROWSEG 14 ;
        SOURCE BRANCH 15 ;
        PATH (0.427,0.149)(0.146,0.149)(0.146,0.197) ;
        LABEL 'Test Results' ;
        SINK BOX 1C1 ;
      ENDSEG ;
      ARROWSEG 15 ;
        SOURCE BRANCH 1 ;
        PATH (0.427,0.147)(0.427,0.149) ;
        LABEL 'Test Results' ;
        SINK BRANCH 13 14 ;
      ENDSEG ;
      ARROWSEG 16 ;
        SOURCE BRANCH 1 ;
        PATH (0.427,0.147)(0.709,0.147)(0.709,0.688) ;
        LABEL 'Test Results' ;
        SINK BOX 3C1 ;
      ENDSEG ;
    ENDDIAGRAM ;
  ENDMODEL ;
ENDKIT ;
